#$Id: perl-Apache-ParseFormData.spec.in,v 1.6 2007/01/05 01:17:04 bpbuild Exp $
Epoch: 2
Distribution: Custom
Vendor: biopackages.net
Summary: Perl extension for dealing with client request data
Name: perl-Apache-ParseFormData
Version: 0.09
Release: 1.7.%{distro}
Packager: contact@seanmcollins.com
License: GPL or Artistic
Group: Development/Libraries
URL: http://search.cpan.org/dist/Apache-ParseFormData/
BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root
BuildArch: noarch
Requires: mod_perl >= 2.0.0
BuildRequires: perl, biopackages 

Patch0: Apache-ParseFormData-%{version}.mp2.patch
Source0: Apache-ParseFormData-%{version}.tar.gz

%description
Apache/ParseFormData version 0.09
=================================

The Apache::ParseFormData module allows you to easily decode and parse
form and query data, even multipart forms generated by "file upload".

This module only work with mod_perl-2.0

INSTALLATION

To install this module type the following:

   perl Makefile.PL
   make
   make test
   make install

DEPENDENCIES

This module requires these other modules and libraries:

  mod_perl-2.0
  perl 5.8 or greater

BUG REPORTS AND SUGGESTIONS

Questions, bug reports, useful code bits, and suggestions for
Apache::ParseFormData hould just be sent to me at hdias@aesbuc.pt

COPYRIGHT AND LICENCE

Copyright (C) 2003 Henrique Dias. All rights reserved.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.


%prep
%setup -q -n Apache-ParseFormData-%{version}
%patch0 -p1

%build
CFLAGS="$RPM_OPT_FLAGS" perl Makefile.PL PREFIX=$RPM_BUILD_ROOT%{_prefix}  < /dev/null
make OPTIMIZE="$RPM_OPT_FLAGS"

%install
rm -rf $RPM_BUILD_ROOT

eval `perl '-V:installarchlib'`
mkdir -p $RPM_BUILD_ROOT$installarchlib
%makeinstall

find $RPM_BUILD_ROOT -type f -a \( -name perllocal.pod -o -name .packlist \
  -o \( -name '*.bs' -a -empty \) \) -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null ';'
chmod -R u+w $RPM_BUILD_ROOT/*

[ -x %{_usr}/lib/rpm/brp-compress ] && %{_usr}/lib/rpm/brp-compress

find $RPM_BUILD_ROOT -type f \
| sed "s@^$RPM_BUILD_ROOT@@g" \
> %{name}-%{version}-%{release}-filelist

eval `perl -V:archname -V:installsitelib -V:installvendorlib -V:installprivlib`
for d in $installsitelib $installvendorlib $installprivlib; do
  [ -z "$d" -o "$d" = "UNKNOWN" -o ! -d "$RPM_BUILD_ROOT$d" ] && continue
  find $RPM_BUILD_ROOT$d/* -type d \
  | grep -v "/$archname\(/auto\)\?$" \
  | sed "s@^$RPM_BUILD_ROOT@%dir @g" \
  >> %{name}-%{version}-%{release}-filelist
done

if [ "$(cat %{name}-%{version}-%{release}-filelist)X" = "X" ] ; then
    echo "ERROR: EMPTY FILE LIST"
    exit 1
fi

%clean
rm -rf $RPM_BUILD_ROOT

%files -f %{name}-%{version}-%{release}-filelist
%defattr(-,root,root,-)

%changelog
* Mon Jan 11 2010 Sean Collins <contact@seanmcollins.com> 0.09-1.7
- Updated deps

* Fri Jan 05 2007 bpbuild bpbuild 0.09-1.6
- Updated deps
* Fri Jan 05 2007 bpbuild bpbuild 0.09-1.5
- Updated deps
* Sat Jul 15 2006 boconnor boconnor 0.09-1.4
- I updated the hardcoded /usr directory in all the spec files.  This
  was to support MacOS which installs all RPMs into /usr/local.  It
  uses a RPM macro now to make it platform neutral.  I've also updated
  some other SPEC files to support MacOS, I've done my best to ensure
  any changes don't affect other platforms negatively
* Tue Jun 27 2006 boconnor boconnor 0.09-1.3
- 1.0 release of Turnkey
* Tue Jun 20 2006 allenday allenday 0.09-1.2
- patch for mp2 2.0.0 rc3
* Fri Jan 27 2006 allenday allenday 0.09-1.1
- import
